apiVersion: v1
kind: ConfigMap
metadata:
  name: search-engine-configmap
data:
  JWT_SECRET: '{{ .Values.JWT_SECRET }}'
  SERVER_BASEPATH: '{{ .Values.SERVER_BASEPATH }}'

  MYSQL_DATABASE: '{{ .Values.MYSQL_DATABASE }}'
  MYSQL_PASSWORD: '{{ .Values.MYSQL_PASSWORD }}'
  MYSQL_ROOT_PASSWORD: '{{ .Values.MYSQL_ROOT_PASSWORD }}'
  MYSQL_USER: '{{ .Values.MYSQL_USER }}'

  SEARCH_ENGINE_SERVER__HOST: '{{ .Values.global.SEARCH_ENGINE_SERVER__HOST }}'
  SEARCH_ENGINE_SERVER__PORT: '{{ .Values.global.SEARCH_ENGINE_SERVER__PORT }}'

  SEARCH_ENGINE_STORAGE__HOST: '{{ .Values.global.SEARCH_ENGINE_STORAGE__HOST }}'
  SEARCH_ENGINE_STORAGE__PORT: '{{ .Values.global.SEARCH_ENGINE_STORAGE__PORT }}'
  SEARCH_ENGINE_STORAGE__USER: '{{ .Values.global.SEARCH_ENGINE_STORAGE__USER }}'
  SEARCH_ENGINE_STORAGE__PASSWORD: '{{ .Values.global.SEARCH_ENGINE_STORAGE__PASSWORD }}'
  SEARCH_ENGINE_STORAGE__DATABASE: '{{ .Values.global.SEARCH_ENGINE_STORAGE__DATABASE }}'

  SEARCH_ENGINE_ELASTIC_APM__SERVICE_NAME: '{{ .Values.global.SEARCH_ENGINE_ELASTIC_APM__SERVICE_NAME }}'
  SEARCH_ENGINE_ELASTIC_APM__SECRET_TOKEN: '{{ .Values.global.SEARCH_ENGINE_ELASTIC_APM__SECRET_TOKEN }}'
  SEARCH_ENGINE_ELASTIC_APM__URL: '{{ .Values.global.SEARCH_ENGINE_ELASTIC_APM__URL }}'

  SEARCH_ENGINE_LOGSTASH__HOST: '{{ .Values.global.SEARCH_ENGINE_LOGSTASH__HOST }}'
  SEARCH_ENGINE_LOGSTASH__PORT: '{{ .Values.global.SEARCH_ENGINE_LOGSTASH__PORT }}'

  SEARCH_ENGINE_REDIS__HOST: '{{ .Values.global.SEARCH_ENGINE_REDIS__HOST }}'
  SEARCH_ENGINE_REDIS__PORT: '{{ .Values.global.SEARCH_ENGINE_REDIS__PORT }}'
  SEARCH_ENGINE_REDIS__PASSWORD: '{{ .Values.global.SEARCH_ENGINE_REDIS__PASSWORD }}'
  SEARCH_ENGINE_REDIS__DB: '{{ .Values.global.SEARCH_ENGINE_REDIS__DB }}'

  SEARCH_ENGINE_RABBIT__HOST: '{{ .Values.global.SEARCH_ENGINE_RABBIT__HOST }}'
  SEARCH_ENGINE_RABBIT__PORT: '{{ .Values.global.SEARCH_ENGINE_RABBIT__PORT }}'
  SEARCH_ENGINE_RABBIT__PASSWORD: '{{ .Values.global.SEARCH_ENGINE_RABBIT__PASSWORD }}'
  SEARCH_ENGINE_RABBIT__USER: '{{ .Values.global.SEARCH_ENGINE_RABBIT__USER }}'

  SEARCH_ENGINE_UAA__PROTOCOL: '{{ .Values.global.SEARCH_ENGINE_UAA__PROTOCOL }}'
  SEARCH_ENGINE_UAA__HOST: '{{ .Values.global.SEARCH_ENGINE_UAA__HOST }}'
  SEARCH_ENGINE_UAA__PORT: '{{ .Values.global.SEARCH_ENGINE_UAA__PORT }}'

  SEARCH_ENGINE_NEWS_MANAGER__PROTOCOL: '{{ .Values.global.SEARCH_ENGINE_NEWS_MANAGER__PROTOCOL }}'
  SEARCH_ENGINE_NEWS_MANAGER__HOST: '{{ .Values.global.SEARCH_ENGINE_NEWS_MANAGER__HOST }}'
  SEARCH_ENGINE_NEWS_MANAGER__PORT: '{{ .Values.global.SEARCH_ENGINE_NEWS_MANAGER__PORT }}'