apiVersion: v1
kind: ConfigMap
metadata:
  name: search-engine-configmap
data:
  SEARCH_ENGINE_SERVER__HOST: '{{ .Values.SEARCH_ENGINE_SERVER__HOST }}'
  SEARCH_ENGINE_SERVER__PORT: '{{ .Values.SEARCH_ENGINE_SERVER__PORT }}'
  SEARCH_ENGINE_SERVER__BASE_PATH: '{{ .Values.SEARCH_ENGINE_SERVER__BASE_PATH }}'

  SEARCH_ENGINE_STORAGE__HOST: '{{ .Values.SEARCH_ENGINE_STORAGE__HOST }}'
  SEARCH_ENGINE_STORAGE__PORT: '{{ .Values.SEARCH_ENGINE_STORAGE__PORT }}'
  SEARCH_ENGINE_STORAGE__USER: '{{ .Values.SEARCH_ENGINE_STORAGE__USER }}'
  SEARCH_ENGINE_STORAGE__PASSWORD: '{{ .Values.SEARCH_ENGINE_STORAGE__PASSWORD }}'
  SEARCH_ENGINE_STORAGE__DATABASE: '{{ .Values.SEARCH_ENGINE_STORAGE__DATABASE }}'

  SEARCH_ENGINE_ELASTIC_APM__SERVICE_NAME: '{{ .Values.SEARCH_ENGINE_ELASTIC_APM__SERVICE_NAME }}'
  SEARCH_ENGINE_ELASTIC_APM__SECRET_TOKEN: '{{ .Values.SEARCH_ENGINE_ELASTIC_APM__SECRET_TOKEN }}'
  SEARCH_ENGINE_ELASTIC_APM__URL: '{{ .Values.SEARCH_ENGINE_ELASTIC_APM__URL }}'

  SEARCH_ENGINE_REDIS__HOST: '{{ .Values.SEARCH_ENGINE_REDIS__HOST }}'
  SEARCH_ENGINE_REDIS__PORT: '{{ .Values.SEARCH_ENGINE_REDIS__PORT }}'
  SEARCH_ENGINE_REDIS__PASSWORD: '{{ .Values.SEARCH_ENGINE_REDIS__PASSWORD }}'

  SEARCH_ENGINE_RABBIT__HOST: '{{ .Values.SEARCH_ENGINE_RABBIT__HOST }}'
  SEARCH_ENGINE_RABBIT__PORT: '{{ .Values.SEARCH_ENGINE_RABBIT__PORT }}'
  SEARCH_ENGINE_RABBIT__PASSWORD: '{{ .Values.SEARCH_ENGINE_RABBIT__PASSWORD }}'
  SEARCH_ENGINE_RABBIT__USER: '{{ .Values.SEARCH_ENGINE_RABBIT__USER }}'

  SEARCH_ENGINE_IAM_JWKS_PATH: '{{ .Values.SEARCH_ENGINE_IAM_JWKS_PATH }}'
  SEARCH_ENGINE_ELASTICSEARCH_HOSTS: '{{ .Values.SEARCH_ENGINE_ELASTICSEARCH_HOSTS }}'
