apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: search-engine-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
        - path: /search/?(.*)
          pathType: Prefix
          backend:
            service:
              name: search-engine
              port:
                number: 8083