apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-search-engine
  name: mysql-search-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-search-engine
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysql-search-engine
    spec:
      containers:
      - args:
        - --default-authentication-plugin=mysql_native_password
        envFrom:
          - configMapRef:
              name: search-engine-configmap
        image: mysql:latest
        imagePullPolicy: ""
        name: mysql-search-engine
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-search-engine-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mysql-search-engine-data
        persistentVolumeClaim:
          claimName: mysql-search-engine-data
status: {}
