apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: search-engine
  name: search-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: search-engine
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: search-engine
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: search-engine-configmap
        image: djrevok/search-engine:latest
        name: search-engine
        ports:
        - containerPort: 8083
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
