apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: search-engine-new-saved-consumer
  name: search-engine-new-saved-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: search-engine-new-saved-consumer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: search-engine-new-saved-consumer
    spec:
      initContainers:
      - name: search-engine-migrations
        image: 'djrevok/search-engine:{{ .Chart.AppVersion }}'
        workingDir: /app/app/migrations
        command:
          - alembic
          - upgrade
          - head
        envFrom:
          - configMapRef:
              name: search-engine-configmap
      containers:
      - envFrom:
          - configMapRef:
              name: search-engine-configmap
        image: 'djrevok/search-engine:{{ .Chart.AppVersion }}'
        name: search-engine-new-saved-consumer
        resources: {}
        command:
          - make
          - run_kombu_event_consumer
          - CONSUMER_NAME=event_consumer.search_engine.index_new.new_saved
      restartPolicy: Always
      serviceAccountName: ""
status: {}
