apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: search-engine-web-server
  name: search-engine-web-server
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/name: search-engine-web-server
status:
  loadBalancer: {}
