apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: search-engine-postgres
  name: search-engine-postgres
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/name: search-engine-postgres
status:
  loadBalancer: {}
