apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: search-engine
  name: search-engine
spec:
  containers:
  - envFrom:
      - configMapRef:
          name: search-engine-configmap
    image: djrevok/search-engine:latest
    name: search-engine
    ports:
    - containerPort: 8083
    resources: {}
  restartPolicy: OnFailure
status: {}
