apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: search-engine
  name: search-engine
spec:
  containers:
  - envFrom:
      - configMapRef:
          name: search-engine-configmap
    image: djrevok/search-engine:latest
    livenessProbe:
      exec:
        command:
        - curl -f http://localhost:8083/healthcheck
      failureThreshold: 10
      periodSeconds: 2
      timeoutSeconds: 20
    name: search-engine
    ports:
    - containerPort: 8083
    resources: {}
  restartPolicy: OnFailure
status: {}
