JWT_SECRET: t0k3ns3cr3t
SERVER_BASEPATH: /search

SEARCH_ENGINE_SERVER__HOST: 0.0.0.0
SEARCH_ENGINE_SERVER__PORT: 8083

SEARCH_ENGINE_STORAGE__HOST: mysql-search-engine
SEARCH_ENGINE_STORAGE__PORT: 3306
SEARCH_ENGINE_STORAGE__USER: app-us3r
SEARCH_ENGINE_STORAGE__PASSWORD: n3wsp4ssw0rd
SEARCH_ENGINE_STORAGE__DATABASE: search-engine

SEARCH_ENGINE_ELASTIC_APM__SERVICE_NAME: search-engine
SEARCH_ENGINE_ELASTIC_APM__SECRET_TOKEN: xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44
SEARCH_ENGINE_ELASTIC_APM__URL: http://apm-server:8200

SEARCH_ENGINE_LOGSTASH__HOST: logstash
SEARCH_ENGINE_LOGSTASH__PORT: 5000

SEARCH_ENGINE_REDIS__HOST: redis
SEARCH_ENGINE_REDIS__PORT: 6379
SEARCH_ENGINE_REDIS__PASSWORD: n3wsr3d1sp4ss
SEARCH_ENGINE_REDIS__DB: 1

SEARCH_ENGINE_RABBIT__HOST: rabbitmq
SEARCH_ENGINE_RABBIT__PORT: 5672
SEARCH_ENGINE_RABBIT__PASSWORD: guest
SEARCH_ENGINE_RABBIT__USER: guest

SEARCH_ENGINE_UAA__PROTOCOL: http
SEARCH_ENGINE_UAA__HOST: uaa
SEARCH_ENGINE_UAA__PORT: 8081

SEARCH_ENGINE_NEWS_MANAGER__PROTOCOL: http
SEARCH_ENGINE_NEWS_MANAGER__HOST: news-manager
SEARCH_ENGINE_NEWS_MANAGER__PORT: 8080

MYSQL_DATABASE: search-engine
MYSQL_PASSWORD: n3wsp4ssw0rd
MYSQL_ROOT_PASSWORD: n3wss3rv1c3
MYSQL_USER: app-us3r

redis:
  REDIS_PASSWORD: n3wsr3d1sp4ss

rabbit:
  RABBITMQ_DEFAULT_PASS: guest
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_VHOST: /