name: Search Engine Service

on:
  push:
    branches-ignore:
      - master

jobs:

  search-engine-CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.9
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements-prod.txt
      - name: Check formatting
        run: tox -e black -- --check
      - name: Check style
        run: tox -e flake8
      - name: Test with unittest
        run: tox -e tests
      - name: Generate coverage report
        run: tox -e coverage_report
      - name: Build the docker image
        run: docker build -t djrevok/search-engine:latest .
      - name: Login to docker hub
        if: github.ref == 'refs/heads/develop'
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish docker image
        if: github.ref == 'refs/heads/develop'
        uses: actions-hub/docker@master
        with:
          args: push djrevok/search-engine:latest
